require 'active_model_serializers'
require 'rspec/rails'
require 'action_controller/serialization_assertions'
require 'rspec/active_model_serializers/version'
require 'rspec/active_model_serializers/matchers'
